name: admin_panel_user_search
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  bloc: ^8.1.1
  injectable: ^2.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_form_builder: ^7.7.0
  get_it: ^7.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
  - family: Avenir
    fonts:
      - asset: fonts/AvenirNext-Regular.ttf
      - asset: fonts/AvenirNext-Bold.ttf
        weight: 600 # SemiBold